version: '3'  # Version of the Docker Compose file format

services:
  load-balancer:
    image: load-balancer:latest
    ports:
      - "80:80"
    networks:
      - load-balancer
    command: ["8081", "8082", "8083"]
    environment:
      - GATEWAY_ADDRESS=172.18.0.1
  server-1:
    image: server:latest
    ports:
      - "8081:8081"
    networks:
      - load-balancer
    command: ["8081"]
  server-2:
    image: server:latest
    ports:
      - "8082:8082"
    networks:
      - load-balancer
    command: ["8082"]
  server-3:
    image: server:latest
    ports:
      - "8083:8083"
    networks:
      - load-balancer
    command: ["8083"]

networks:
  load-balancer:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1