apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-balancer
  template:
    metadata:
      labels:
        app: load-balancer
    spec:
      containers:
      - name: load-balancer
        image: load-balancer:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80        
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  ARG1: "8081"
  ARG2: "8082"
  ARG3: "8083"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: server:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: server-config

     
